PA2021-105-Competencias
PlanAcad/PlanAcadProject pull request #51
Opened 2021-11-14 20:23 UTC by lucasmmaidana

Bug: https://proyecto-final-2021.atlassian.net/browse/PA2021-105

Cambié las subcompetencias para que sea un textarea de competencia. Así se planteó en el figma
La entidad subcompetencia sigue existiendo pero quedó inaccesible

2021-11-16 13:41 UTC, nicmalegre requested changes

2021-11-16 13:41 UTC, nicmalegre commented on planacad/planificaciones/modelos/modelCompetencia.py
> +   subcompetencias = models.TextField(max_length=700,blank=True, null=True)
Hay que tener cuidado con esto porque en la sección 6 se utilizan las subcompetencias para distinguir por propuesta de desarrollo. Es decir, para cada propuesta de desarrollo podes seleccionar que subcompetencia quieres asociarla. Si todas están dentro de un TextField no se va a poder. Deberíamos definir como va a quedar y que priorizamos. 
![image](https://user-images.githubusercontent.com/40902023/141995951-26dc261b-bee7-449f-931d-dbf7bd186fe5.png)

2021-11-18 21:54 UTC, CarlosLopezSoto commented on planacad/planificaciones/modelos/modelCompetencia.py
> +   subcompetencias = models.TextField(max_length=700,blank=True, null=True)
a mi tampoco me parece lo mejor juntarlo

2021-11-18 22:38 UTC, CarlosLopezSoto submitted a review, later dismissed

2021-12-07 21:54 UTC, closed without merging